"""empty message

Revision ID: c643fe81637c
Revises: 
Create Date: 2019-07-18 16:56:36.474358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c643fe81637c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('login_time', sa.DateTime(), nullable=True),
    sa.Column('logout_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('street', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('no_of_floors', sa.Integer(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guestId', sa.Integer(), nullable=False),
    sa.Column('full_names', sa.String(length=128), nullable=False),
    sa.Column('phone_no', sa.BigInteger(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('reason_for_visit', sa.String(length=128), nullable=False),
    sa.Column('time_in', sa.DateTime(), nullable=True),
    sa.Column('time_out', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('door_or_room', sa.String(length=128), nullable=True),
    sa.Column('floor_number', sa.Integer(), nullable=False),
    sa.Column('phone_no', sa.BigInteger(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_no')
    )
    op.create_table('guards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guardId', sa.Integer(), nullable=False),
    sa.Column('guard_name', sa.String(length=128), nullable=False),
    sa.Column('phone_no', sa.BigInteger(), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('security_company', sa.String(length=128), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guardId'),
    sa.UniqueConstraint('phone_no')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employeeId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('phone_no', sa.BigInteger(), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=128), nullable=False),
    sa.Column('time_in', sa.DateTime(), nullable=True),
    sa.Column('time_out', sa.DateTime(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sign_in_guests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guard_id', sa.Integer(), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('guest_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['guard_id'], ['guards.id'], ),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sign_in_employees',
    sa.Column('guard_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['guard_id'], ['guards.id'], ),
    sa.PrimaryKeyConstraint('guard_id', 'employee_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sign_in_employees')
    op.drop_table('sign_in_guests')
    op.drop_table('employees')
    op.drop_table('guards')
    op.drop_table('companies')
    op.drop_table('guests')
    op.drop_table('buildings')
    op.drop_table('app_logs')
    # ### end Alembic commands ###
